name: actionlint
description: actionlint action
inputs:
  github_token:
    description: 'GitHub Access Token'
    required: false
    default: ${{ github.token }}
  actionlint_options:
    description: actionlint's command line options
    required: false
runs:
  using: composite
  steps:
    - name: 'Link to Action: https://github.com/suzuki-shunsuke/github-action-actionlint'
      run: |
        echo "::debug::Link to Action: https://github.com/suzuki-shunsuke/github-action-actionlint"
      shell: bash

    - run: |
        echo "::error ::github_token is required. https://github.com/suzuki-shunsuke/github-action-actionlint"
        exit 1
      shell: bash
      if: inputs.github_token == ''

    - uses: aquaproj/aqua-installer@9ebf656952a20c45a5d66606f083ff34f58b8ce0 # v4.0.0
      with:
        aqua_version: v2.53.0
        skip_install_aqua: "true"

    - run: |
        export AQUA_GLOBAL_CONFIG=${AQUA_GLOBAL_CONFIG:-}:$GITHUB_WORKSPACE/aqua.yaml
        actionlint -version
        reviewdog -version
        shellcheck -V
      shell: bash
    - name: actionlint
      shell: bash
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github_token }}
        ACTIONLINT_OPTIONS: ${{ inputs.actionlint_options }}
      run: |
        export AQUA_GLOBAL_CONFIG=${AQUA_GLOBAL_CONFIG:-}:$GITHUB_WORKSPACE/aqua.yaml
        reporter=github-check
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          reporter=github-pr-review
        fi

        if ( reviewdog --help 2>&1 || : ) | grep -- "-fail-level" >/dev/null; then
          echo "use -fail-level" >&2
          options="-fail-level=error"
        else
          echo "use -fail-on-error" >&2
          options="-fail-on-error=1"
        fi

        actionlint $ACTIONLINT_OPTIONS |
          reviewdog \
            -efm="%f:%l:%c: %m" \
            -name="actionlint" \
            -filter-mode=nofilter \
            -reporter="$reporter" \
            -level=warning \
            "$options"
